import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const webRoot = path.resolve('tools', 'osdcloud-tui', 'web');

test('web UI exposes dashboard view topology', () => {
  const html = fs.readFileSync(path.join(webRoot, 'index.html'), 'utf8');
  const script = fs.readFileSync(path.join(webRoot, 'app.js'), 'utf8');
  const styles = fs.readFileSync(path.join(webRoot, 'styles.css'), 'utf8');

  assert.match(html, /id="tailwind-config"/);
  assert.match(html, /cdn\.tailwindcss\.com\?plugins=forms,container-queries/);
  assert.match(html, /bg-surface text-on-surface min-h-screen flex flex-col font-body-sm/);
  assert.match(html, /dashboard-grid grid grid-cols-12 gap-sm/);
  assert.match(html, /dashboard-operations-column/);
  assert.match(html, /dashboard-status-column/);
  assert.match(html, /dashboard-log-column/);
  assert.match(html, /id="view-dashboard"/);
  assert.doesNotMatch(html, /id="view-endpoints"/);
  assert.doesNotMatch(html, /id="view-sync"/);
  assert.doesNotMatch(html, /id="view-validation"/);
  assert.doesNotMatch(html, /class="nav-button/);
  assert.doesNotMatch(html, /data-view=/);
  assert.match(html, /id="endpoint-settings-dialog"/);
  assert.match(html, /id="deployment-profiles-dialog"/);
  assert.match(html, /id="os-images-dialog"/);
  assert.match(html, /class="drawer-dialog os-images-dialog"/);
  assert.match(html, /class="dialog-card drawer-card drawer-card-wide os-images-card"/);
  assert.match(html, /id="validation-evidence-dialog"/);
  assert.match(html, /OS Image Cache/);
  assert.match(html, /Local Import/);
  assert.match(html, /Microsoft Official Downloads/);
  assert.match(html, /Upload file/);
  assert.match(html, /id="os-filter-release"/);
  assert.match(html, /id="os-upload-file"/);
  assert.doesNotMatch(html, /Host path/);
  assert.doesNotMatch(html, /id="os-import-source"/);
  assert.match(html, /id="os-load-catalog-button"/);
  assert.match(html, /Windows 11 Pro Retail only/);
  assert.doesNotMatch(html, /name="os-catalog-family"/);
  assert.doesNotMatch(html, /value="win10"/);
  assert.doesNotMatch(html, /name="os-catalog-activation"/);
  assert.doesNotMatch(html, /name="os-catalog-source"/);
  assert.doesNotMatch(html, /id="os-filter-activation"/);
  assert.doesNotMatch(html, /id="os-filter-source"/);
  assert.match(html, /name="os-catalog-language"/);
  assert.match(html, /value="en-us"/);
  assert.match(html, /value="zh-cn"/);
  assert.match(html, /value="zh-tw"/);
  assert.match(html, /value="ja-jp"/);
  assert.match(html, /value="ko-kr"/);
  assert.match(html, /value="vi-vn"/);
  assert.match(html, /value="th-th"/);
  assert.match(html, /value="id-id"/);
  assert.match(html, /value="es-es"/);
  assert.match(html, /name="os-catalog-release"/);
  assert.match(html, /Release <span class="subtle">required<\/span>/);
  assert.match(html, /value="25H1"/);
  assert.match(html, /value="25H2"/);
  assert.match(html, /value="26H1"/);
  assert.match(html, /value="26H2"/);
  assert.match(html, /26H1\/26H2 may not be available in the Microsoft download catalog yet\./);
  assert.doesNotMatch(html, /value="27H1"/);
  assert.doesNotMatch(html, /value="27H2"/);
  assert.doesNotMatch(html, /Not available yet/);
  assert.doesNotMatch(html, /value="21H2"/);
  assert.doesNotMatch(html, /value="22H2"/);
  assert.doesNotMatch(html, /value="23H2"/);
  assert.doesNotMatch(html, /value="24H2"/);
  assert.match(html, /Refine loaded results/);
  assert.doesNotMatch(html, />Source</);
  assert.match(html, /aria-live="polite"/);
  assert.match(styles, /\.os-images-dialog/);
  assert.match(styles, /width: min\(1480px, calc\(100vw - 40px\)\)/);
  assert.match(styles, /\.os-cache-table \{\s*min-width: 980px;/);
  assert.match(styles, /\.os-download-catalog-table \{\s*min-width: 1180px;/);
  assert.match(styles, /\.os-import-table \{\s*min-width: 960px;/);
  assert.match(styles, /\.local-import-grid/);
  assert.match(html, /Endpoint Sync Progress/);
  assert.match(html, /data-action="preflight" data-icon="fact_check" type="button">Run preflight/);
  assert.doesNotMatch(html, /data-action="preflight"[^>]*primary-action/);
  assert.match(html, /data-action="endpoint-sync" data-icon="sync_alt" class="warning"/);
  assert.match(html, /id="preflight-status-badge"[^>]*aria-live="polite"/);
  assert.match(html, /Validation Evidence/);
  assert.match(html, /Refresh Evidence/);
  assert.doesNotMatch(script, /switchView\(/);
  assert.match(script, /openDialog\(elements\.endpointSettingsDialog\)/);
  assert.match(script, /openDialog\(elements\.deploymentProfilesDialog\)/);
  assert.match(script, /openDialog\(elements\.osImagesDialog\)/);
  assert.match(script, /openDialog\(elements\.validationEvidenceDialog\)/);
  assert.match(script, /handleOsImageSelect/);
  assert.match(script, /handleOsImageDelete/);
  assert.match(script, /\/api\/os-image-delete/);
  assert.match(script, /dataset\.osImageAction = 'delete'/);
  assert.match(script, /Delete cached OS image/);
  assert.match(script, /handleOsImageDownload/);
  assert.match(script, /osDownloadStarting/);
  assert.match(script, /\/api\/os-download/);
  assert.match(script, /Starting\.\.\./);
  assert.match(script, /Downloading \$\{bytes\(downloadStatus\.bytes\)\}/);
  assert.doesNotMatch(script, /mutate\('\/api\/os-download'/);
  assert.match(script, /handleOsImageUploadInspect/);
  assert.match(script, /handleOsImageImport/);
  assert.doesNotMatch(script, /handleOsImageInspect/);
  assert.doesNotMatch(script, /\/api\/os-image-inspect/);
  assert.doesNotMatch(script, /\/api\/os-image-import/);
  assert.match(script, /osDownloadCatalogLoading/);
  assert.match(script, /osDownloadCatalogError/);
  assert.match(script, /selectedOsCatalogFilters/);
  assert.match(script, /edition: \['Pro'\]/);
  assert.match(script, /activation: \['Retail'\]/);
  assert.match(script, /missing\.push\('release'\)/);
  assert.match(script, /Select at least one release before loading the catalog/);
  assert.match(script, /catalogFilterQuery/);
  assert.match(script, /osFamily/);
  assert.doesNotMatch(script, /checkedValues\('os-catalog-family'\)/);
  assert.doesNotMatch(script, /checkedValues\('os-catalog-activation'\)/);
  assert.doesNotMatch(script, /checkedValues\('os-catalog-source'\)/);
  assert.match(script, /Loading Microsoft official Windows image catalog/);
  assert.match(script, /\/api\/os-image-upload/);
  assert.match(script, /\/api\/os-image-upload-import/);
  assert.match(script, /Loading catalog\.\.\./);
  assert.match(script, /Catalog load failed/);
  assert.match(script, /No catalog rows matched the selected filters/);
  assert.match(script, /dataset\.runAction = 'evidence'/);
  assert.match(script, /showValidationEvidence/);
  assert.match(script, /elements\.confirmSubmit\.classList\.toggle\('warning', resolvedSeverity === 'warning'\)/);
  assert.match(script, /severity: 'warning'/);
  assert.match(html, /Material\+Symbols\+Outlined/);
  assert.match(html, /Inter:wght@400;500;600/);
  assert.match(html, />Operations</);
  assert.match(html, />System Log</);
  assert.doesNotMatch(html, /Quick Actions/);
  assert.doesNotMatch(html, /quick-actions-panel/);
  assert.doesNotMatch(html, /```html/);
});

test('web UI uses confirmation dialog instead of window confirm', () => {
  const html = fs.readFileSync(path.join(webRoot, 'index.html'), 'utf8');
  const script = fs.readFileSync(path.join(webRoot, 'app.js'), 'utf8');

  assert.match(html, /id="confirm-dialog"/);
  assert.doesNotMatch(script, /window\.confirm/);
});

test('web UI uses a single stateful all-services toggle', () => {
  const html = fs.readFileSync(path.join(webRoot, 'index.html'), 'utf8');
  const script = fs.readFileSync(path.join(webRoot, 'app.js'), 'utf8');

  assert.match(html, /data-action="all-services-toggle"/);
  assert.doesNotMatch(html, /data-action="start-all"/);
  assert.doesNotMatch(html, /data-action="stop-all"/);
  assert.match(script, /action === 'all-services-toggle'/);
  assert.match(script, /Stop all services/);
  assert.match(script, /Start all services/);
});

test('web UI makes service cards stateful toggles', () => {
  const script = fs.readFileSync(path.join(webRoot, 'app.js'), 'utf8');
  const styles = fs.readFileSync(path.join(webRoot, 'styles.css'), 'utf8');

  assert.match(script, /row\.dataset\.action = action/);
  assert.match(script, /row\.setAttribute\('role', 'button'\)/);
  assert.match(script, /row\.setAttribute\('aria-label', actionLabel\)/);
  assert.match(script, /row\.setAttribute\('tabindex', '0'\)/);
  assert.match(script, /'http-toggle'/);
  assert.match(script, /'tftp-toggle'/);
  assert.match(script, /'dhcp-toggle'/);
  assert.match(script, /button\[data-action="\$\{action\}"\]/);
  assert.match(script, /makeStatusPill\(service\.running \? 'Running' : 'Stopped', service\.running \? 'ok' : 'neutral'\)/);
  assert.match(script, /cardAction\.className = `service-card-cta\$\{action === 'dhcp-toggle' && !service\.running \? ' danger' : ''\}`/);
  assert.match(script, /cardAction\.dataset\.icon = service\.running \? 'stop' : 'play_arrow'/);
  assert.match(script, /service-card-action\[data-action\]/);
  assert.match(styles, /\.service-card-cta/);
  assert.match(styles, /\.service-card-cta\.danger/);
  assert.match(styles, /\.service-card\[data-service-state="stopped"\] \.service-switch/);
  assert.match(styles, /\.service-switch\.running \{\s*background: var\(--ok\);/);
  assert.match(styles, /\.status-services-grid \{\s*grid-template-columns: minmax\(0, 1fr\) !important;/);
  assert.match(styles, /\.service-card-action:hover/);
  assert.match(styles, /\.service-card-action:focus-visible/);
});

test('operations buttons use neutral, warning, and danger severity without blue default', () => {
  const html = fs.readFileSync(path.join(webRoot, 'index.html'), 'utf8');
  const script = fs.readFileSync(path.join(webRoot, 'app.js'), 'utf8');
  const styles = fs.readFileSync(path.join(webRoot, 'styles.css'), 'utf8');

  assert.doesNotMatch(html, /quiet-action/);
  assert.doesNotMatch(html, /primary-action/);
  assert.doesNotMatch(styles, /button\.quiet-action/);
  assert.doesNotMatch(styles, /button\.primary-action/);
  assert.match(styles, /button \{\s*appearance: none;[\s\S]*font: 500 12px\/16px Inter, sans-serif;/);
  assert.match(styles, /button\.warning/);
  assert.match(styles, /button\.all-services-toggle\.is-running \{\s*border-color: var\(--outline\);[\s\S]*color: var\(--on-surface\);/);
  assert.match(script, /button\.className = active \? '' : 'warning'/);
  assert.match(script, /select\.className = 'warning'/);
  assert.match(script, /sync\.className = 'warning'/);
  assert.match(script, /return \['Blocked', 'fail'\]/);
});

test('web UI keeps local component layer', () => {
  const styles = fs.readFileSync(path.join(webRoot, 'styles.css'), 'utf8');
  const script = fs.readFileSync(path.join(webRoot, 'app.js'), 'utf8');

  assert.match(styles, /--primary-container: #1e3a8a/);
  assert.match(styles, /\.view\.active/);
  assert.match(styles, /\.service-switch/);
  assert.match(styles, /\.preflight-summary-list/);
  assert.match(styles, /-webkit-line-clamp: 2/);
  assert.match(styles, /\.dashboard-operations-column/);
  assert.match(styles, /\.dashboard-status-column/);
  assert.match(styles, /\.dashboard-log-column/);
  assert.match(script, /makeIcon/);
  assert.match(script, /service-card/);
  assert.match(script, /card-icon/);
  assert.match(script, /service-row-head/);
  assert.match(script, /checks passed/);
});
