# Stages the Microsoft-signed PXE boot tree under PXE-TFTP for the secureboot boot mode.
#
# Layout staged under <LiveRoot>\PXE-TFTP:
#   bootmgfw.efi               copy of Media\EFI\Boot\bootx64.efi (Microsoft-signed boot manager)
#   Boot\BCD                   network BCD store generated by bcdedit (ramdisk boot of sources\boot.wim)
#   Boot\boot.sdi              copy of Media\Boot\boot.sdi
#   Boot\Fonts\*.ttf           copies of Media\Boot\Fonts
#   Boot\Resources\*           copies of Media\Boot\Resources (bootres.dll)
#   EFI\Microsoft\Boot\        boot.stl (Secure Boot revocation list) and Fonts\*.ttf — PXE-booted
#                              bootmgr requests these under \EFI\Microsoft\Boot first (optional,
#                              boots without them; staged to satisfy the lookup)
#   sources\boot.wim           hardlink to PXE-HttpRoot\osdcloud\boot.wim (copy fallback across volumes)
#
# Contract: every publish of PXE-HttpRoot\osdcloud\boot.wim must be followed by a run of
# this script so the sources\boot.wim hardlink is re-verified (publishers that replace the
# file instead of overwriting it in place would otherwise strand the link).
[CmdletBinding()]
param(
    [string] $LiveRoot = 'C:\OSDCloud',
    [switch] $DryRun
)

$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = $Utf8NoBom
$OutputEncoding = $Utf8NoBom

$ErrorActionPreference = 'Stop'

function Invoke-Bcdedit {
    param([Parameter(Mandatory)][string[]] $ArgumentList)

    $output = & bcdedit @ArgumentList 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "bcdedit failed with exit code ${LASTEXITCODE}: bcdedit $($ArgumentList -join ' ')`n$output"
    }
    $output
}

function Assert-MicrosoftSignedBootFile {
    param(
        [Parameter(Mandatory)][string] $Path,
        [Parameter(Mandatory)][string] $Label
    )

    Import-Module Microsoft.PowerShell.Security -ErrorAction Stop
    $signature = Get-AuthenticodeSignature -FilePath $Path -ErrorAction Stop
    if ($signature.Status -ne 'Valid') {
        throw "$Label Authenticode signature is not valid: $($signature.Status) $Path"
    }
    $subject = [string] $signature.SignerCertificate.Subject
    if ($subject -notmatch 'Microsoft Corporation|Microsoft Windows') {
        throw "$Label is not signed by Microsoft: $subject $Path"
    }
    Write-Host "Verified Microsoft signature on $Label ($($signature.SignerCertificate.Subject))"
}

function Get-NtfsFileId {
    param([Parameter(Mandatory)][string] $Path)

    $output = & fsutil file queryfileid $Path 2>&1
    if ($LASTEXITCODE -ne 0) {
        return $null
    }
    $match = [regex]::Match([string] $output, '0x[0-9a-fA-F]+')
    if ($match.Success) { $match.Value } else { $null }
}

function Sync-BootWimHardlink {
    param(
        [Parameter(Mandatory)][string] $PublishedBootWim,
        [Parameter(Mandatory)][string] $TftpBootWim
    )

    if (Test-Path -LiteralPath $TftpBootWim -PathType Leaf) {
        $publishedId = Get-NtfsFileId -Path $PublishedBootWim
        $tftpId = Get-NtfsFileId -Path $TftpBootWim
        if ($publishedId -and $tftpId -and $publishedId -eq $tftpId) {
            Write-Host "TFTP sources\boot.wim already hardlinked to published boot.wim"
            return
        }
        Remove-Item -LiteralPath $TftpBootWim -Force
    }

    try {
        New-Item -ItemType HardLink -Path $TftpBootWim -Target $PublishedBootWim -ErrorAction Stop | Out-Null
        Write-Host "Hardlinked TFTP sources\boot.wim -> $PublishedBootWim"
    }
    catch {
        Copy-Item -LiteralPath $PublishedBootWim -Destination $TftpBootWim -Force
        Write-Host "Copied published boot.wim to TFTP sources\boot.wim (hardlink unavailable: $($_.Exception.Message))"
    }
}

function New-NetworkBcdStore {
    param([Parameter(Mandatory)][string] $StorePath)

    # Regenerated on every run: the store embeds fresh GUIDs each time, so it is
    # validated by existence (not hash) in the runtime artifact catalog.
    Remove-Item -LiteralPath $StorePath -Force -ErrorAction SilentlyContinue
    Invoke-Bcdedit @('/createstore', $StorePath) | Out-Null

    # TFTP transfer tuning must stay within the Node TFTP responder caps
    # (blksize <= 1468, windowsize <= 64 in tools/osdcloud-console/src/tftp.js).
    Invoke-Bcdedit @('/store', $StorePath, '/create', '{ramdiskoptions}', '/d', 'OSDCloud ramdisk options') | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', '{ramdiskoptions}', 'ramdisksdidevice', 'boot') | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', '{ramdiskoptions}', 'ramdisksdipath', '\Boot\boot.sdi') | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', '{ramdiskoptions}', 'ramdisktftpblocksize', '1456') | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', '{ramdiskoptions}', 'ramdisktftpwindowsize', '16') | Out-Null

    $createOutput = Invoke-Bcdedit @('/store', $StorePath, '/create', '/d', 'OSDCloud WinPE (Secure Boot PXE)', '/application', 'osloader')
    $guidMatch = [regex]::Match([string] $createOutput, '\{[0-9a-fA-F-]{36}\}')
    if (-not $guidMatch.Success) {
        throw "bcdedit /create osloader did not return an entry GUID: $createOutput"
    }
    $guid = $guidMatch.Value

    $ramdiskDevice = 'ramdisk=[boot]\sources\boot.wim,{ramdiskoptions}'
    Invoke-Bcdedit @('/store', $StorePath, '/set', $guid, 'device', $ramdiskDevice) | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', $guid, 'osdevice', $ramdiskDevice) | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', $guid, 'path', '\windows\system32\boot\winload.efi') | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', $guid, 'systemroot', '\windows') | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', $guid, 'winpe', 'yes') | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', $guid, 'detecthal', 'yes') | Out-Null

    Invoke-Bcdedit @('/store', $StorePath, '/create', '{bootmgr}', '/d', 'OSDCloud Boot Manager') | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', '{bootmgr}', 'default', $guid) | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', '{bootmgr}', 'displayorder', $guid) | Out-Null
    Invoke-Bcdedit @('/store', $StorePath, '/set', '{bootmgr}', 'timeout', '0') | Out-Null

    Write-Host "Generated network BCD store at $StorePath (osloader $guid)"
}

try {
    $mediaRoot = Join-Path $LiveRoot 'Media'
    $tftpRoot = Join-Path $LiveRoot 'PXE-TFTP'
    $bootManagerSource = Join-Path $mediaRoot 'EFI\Boot\bootx64.efi'
    $bootSdiSource = Join-Path $mediaRoot 'Boot\boot.sdi'
    $fontsSource = Join-Path $mediaRoot 'Boot\Fonts'
    $resourcesSource = Join-Path $mediaRoot 'Boot\Resources'
    $bootStlSource = Join-Path $mediaRoot 'EFI\Microsoft\Boot\boot.stl'
    $efiFontsSource = Join-Path $mediaRoot 'EFI\Microsoft\Boot\Fonts'
    $publishedBootWim = Join-Path $LiveRoot 'PXE-HttpRoot\osdcloud\boot.wim'

    $bootManagerTarget = Join-Path $tftpRoot 'bootmgfw.efi'
    $bcdTarget = Join-Path $tftpRoot 'Boot\BCD'
    $bootSdiTarget = Join-Path $tftpRoot 'Boot\boot.sdi'
    $fontsTarget = Join-Path $tftpRoot 'Boot\Fonts'
    $resourcesTarget = Join-Path $tftpRoot 'Boot\Resources'
    $efiBootTarget = Join-Path $tftpRoot 'EFI\Microsoft\Boot'
    $efiFontsTarget = Join-Path $efiBootTarget 'Fonts'
    $tftpBootWim = Join-Path $tftpRoot 'sources\boot.wim'

    if (-not (Test-Path -LiteralPath $bootManagerSource -PathType Leaf) -or
        -not (Test-Path -LiteralPath $bootSdiSource -PathType Leaf)) {
        Write-Warning "OSDCloud workspace media not found under $mediaRoot; skipping Secure Boot TFTP staging. Run Prepare runtime first."
        exit 0
    }

    if ($DryRun) {
        Write-Host "[dry-run] publish $bootManagerSource -> $bootManagerTarget"
        Write-Host "[dry-run] generate network BCD store at $bcdTarget"
        Write-Host "[dry-run] publish $bootSdiSource -> $bootSdiTarget"
        Write-Host "[dry-run] publish $fontsSource -> $fontsTarget"
        Write-Host "[dry-run] publish $resourcesSource -> $resourcesTarget"
        Write-Host "[dry-run] hardlink $publishedBootWim -> $tftpBootWim"
        exit 0
    }

    New-Item -ItemType Directory -Path @(
        (Join-Path $tftpRoot 'Boot'),
        $fontsTarget,
        $resourcesTarget,
        $efiFontsTarget,
        (Join-Path $tftpRoot 'sources')
    ) -Force | Out-Null

    Copy-Item -LiteralPath $bootManagerSource -Destination $bootManagerTarget -Force
    Assert-MicrosoftSignedBootFile -Path $bootManagerTarget -Label 'Secure Boot PXE boot manager'

    Copy-Item -LiteralPath $bootSdiSource -Destination $bootSdiTarget -Force
    Copy-Item -Path (Join-Path $fontsSource '*.ttf') -Destination $fontsTarget -Force
    if (Test-Path -LiteralPath $resourcesSource -PathType Container) {
        Copy-Item -Path (Join-Path $resourcesSource '*') -Destination $resourcesTarget -Recurse -Force
    }
    else {
        Write-Host "Media Boot\Resources not present; skipping bootres.dll staging."
    }
    if (Test-Path -LiteralPath $bootStlSource -PathType Leaf) {
        Copy-Item -LiteralPath $bootStlSource -Destination (Join-Path $efiBootTarget 'boot.stl') -Force
    }
    else {
        Write-Host "Media EFI\Microsoft\Boot\boot.stl not present; skipping revocation list staging."
    }
    if (Test-Path -LiteralPath $efiFontsSource -PathType Container) {
        Copy-Item -Path (Join-Path $efiFontsSource '*.ttf') -Destination $efiFontsTarget -Force
    }

    New-NetworkBcdStore -StorePath $bcdTarget

    if (Test-Path -LiteralPath $publishedBootWim -PathType Leaf) {
        Sync-BootWimHardlink -PublishedBootWim $publishedBootWim -TftpBootWim $tftpBootWim
    }
    else {
        Write-Warning "Published boot.wim not found at $publishedBootWim; TFTP sources\boot.wim not linked. Re-run after endpoint sync publishes boot.wim."
    }

    Write-Host "Secure Boot TFTP tree ready under $tftpRoot"
}
catch {
    Write-Error $_.Exception.Message
    exit 1
}
